import {
  Music,
  Code,
  Globe,
  Shirt,
  TrendingUp,
  Sparkles,
  ChefHat,
  Camera,
  Pen,
  Brain,
  Dumbbell,
  Scissors,
  Heart,
  Star,
  BookOpen,
  Lightbulb,
  Target,
  Zap,
  Palette,
  Guitar,
  PenTool,
  Briefcase,
  Wrench,
  Leaf,
  Dog,
  Calculator,
  Shield,
  MessageSquare,
  Mic,
  Hand,
  Eye,
  Layers,
  Box,
  Flame,
  Wind,
  Droplets,
  Sun,
  Clock,
  DollarSign,
  CheckCircle,
  Timer,
  Bookmark,
  ArrowDown,
  ArrowUp,
  Home,
  Utensils,
  Map,
  Gamepad2,
  Smartphone,
  Car,
  Compass,
  Puzzle,
  Trophy,
  Headphones,
  Film,
  Tv,
  Brush,
  Flower,
  Mountain,
  Bike,
  Tent,
  Plane,
  Anchor,
  Sailboat,
  Coffee,
  Beer,
  Wine,
  GraduationCap,
  Newspaper,
  Library,
  Radio,
  Hammer,
  Key,
  Lock,
  Umbrella,
  Thermometer,
  Stethoscope,
  Scale,
  Feather,
  Type,
  Terminal,
  Database,
  Server,
  Cpu,
  Wifi,
  Bluetooth,
  Monitor,
  Printer,
  Aperture,
  Crop,
  Grid3x3,
  Move,
  Maximize,
  Minimize,
  Volume2,
  Bell,
  Mail,
  Phone,
  Calendar,
  Clipboard,
  FileText,
  Folder,
  Search,
  Settings,
  Wrench as ToolIcon,
  Users,
  UserPlus,
  Share2,
  Download,
  Upload,
  RefreshCw,
  RotateCw,
  Paperclip,
  Link,
  ExternalLink,
  Play,
  Footprints,
  IceCream2,
  ShoppingBag,
  ShoppingCart,
  MapPin,
  AlarmClock,
  Sunrise,
  Croissant,
  Martini,
  Dice5,
  Landmark,
  Gift,
  Telescope,
  Moon,
  Ticket,
  Trees,
  CloudRain,
  Snowflake,
  Popcorn,
  Sandwich,
  Grape,
  Cherry,
  Apple,
  Egg,
  Flag,
  Dices,
  Menu,
  X,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  PartyPopper,
  Volleyball,
  Waves,
  Clapperboard,
  Paintbrush,
  Pencil,
  NotebookPen,
  Armchair,
  Glasses,
  HandHeart,
  Laugh,
  Gem,
  Crown,
  Ribbon,
  Candy,
  Soup,
  Salad,
  MessageCircleHeart,
  Cake,
  Pizza,
  Train,
  GlassWater,
  Building,
  Theater,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  'music': Music,
  'code': Code,
  'globe': Globe,
  'shirt': Shirt,
  'trending-up': TrendingUp,
  'sparkles': Sparkles,
  'chef-hat': ChefHat,
  'camera': Camera,
  'pen': Pen,
  'brain': Brain,
  'dumbbell': Dumbbell,
  'scissors': Scissors,
  'heart': Heart,
  'star': Star,
  'book-open': BookOpen,
  'lightbulb': Lightbulb,
  'target': Target,
  'zap': Zap,
  'palette': Palette,
  'guitar': Guitar,
  'pen-tool': PenTool,
  'briefcase': Briefcase,
  'wrench': Wrench,
  'leaf': Leaf,
  'dog': Dog,
  'calculator': Calculator,
  'shield': Shield,
  'message-square': MessageSquare,
  'mic': Mic,
  'hand': Hand,
  'eye': Eye,
  'layers': Layers,
  'box': Box,
  'flame': Flame,
  'wind': Wind,
  'droplets': Droplets,
  'sun': Sun,
  'clock': Clock,
  'dollar-sign': DollarSign,
  'check-circle': CheckCircle,
  'timer': Timer,
  'bookmark': Bookmark,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  'home': Home,
  'utensils': Utensils,
  'map': Map,
  'gamepad': Gamepad2,
  'smartphone': Smartphone,
  'car': Car,
  'compass': Compass,
  'puzzle': Puzzle,
  'trophy': Trophy,
  'headphones': Headphones,
  'film': Film,
  'tv': Tv,
  'brush': Brush,
  'flower': Flower,
  'mountain': Mountain,
  'bike': Bike,
  'tent': Tent,
  'plane': Plane,
  'anchor': Anchor,
  'sailboat': Sailboat,
  'coffee': Coffee,
  'beer': Beer,
  'wine': Wine,
  'graduation-cap': GraduationCap,
  'newspaper': Newspaper,
  'library': Library,
  'radio': Radio,
  'hammer': Hammer,
  'key': Key,
  'lock': Lock,
  'umbrella': Umbrella,
  'thermometer': Thermometer,
  'stethoscope': Stethoscope,
  'scale': Scale,
  'feather': Feather,
  'type': Type,
  'terminal': Terminal,
  'database': Database,
  'server': Server,
  'cpu': Cpu,
  'wifi': Wifi,
  'bluetooth': Bluetooth,
  'monitor': Monitor,
  'printer': Printer,
  'aperture': Aperture,
  'crop': Crop,
  'grid': Grid3x3,
  'move': Move,
  'maximize': Maximize,
  'minimize': Minimize,
  'volume': Volume2,
  'bell': Bell,
  'mail': Mail,
  'phone': Phone,
  'calendar': Calendar,
  'clipboard': Clipboard,
  'file-text': FileText,
  'folder': Folder,
  'search': Search,
  'settings': Settings,
  'tool': ToolIcon,
  'users': Users,
  'user-plus': UserPlus,
  'share': Share2,
  'download': Download,
  'upload': Upload,
  'refresh': RefreshCw,
  'rotate': RotateCw,
  'paperclip': Paperclip,
  'link': Link,
  'external-link': ExternalLink,
  'play': Play,
  'footprints': Footprints,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'map-pin': MapPin,
  'alarm-clock': AlarmClock,
  'sunrise': Sunrise,
  'croissant': Croissant,
  'martini': Martini,
  'dice': Dice5,
  'landmark': Landmark,
  'gift': Gift,
  'telescope': Telescope,
  'moon': Moon,
  'ticket': Ticket,
  'trees': Trees,
  'cloud-rain': CloudRain,
  'snowflake': Snowflake,
  'popcorn': Popcorn,
  'sandwich': Sandwich,
  'grape': Grape,
  'cherry': Cherry,
  'apple': Apple,
  'egg': Egg,
  'flag': Flag,
  'dices': Dices,
  'menu': Menu,
  'x': X,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'party-popper': PartyPopper,
  'volleyball': Volleyball,
  'waves': Waves,
  'clapperboard': Clapperboard,
  'paintbrush': Paintbrush,
  'pencil': Pencil,
  'notebook-pen': NotebookPen,
  'armchair': Armchair,
  'glasses': Glasses,
  'hand-heart': HandHeart,
  'laugh': Laugh,
  'gem': Gem,
  'crown': Crown,
  'ribbon': Ribbon,
  'candy': Candy,
  'soup': Soup,
  'salad': Salad,
  'message-circle-heart': MessageCircleHeart,
  'cake': Cake,
  'pizza': Pizza,
  'train': Train,
  'glass-water': GlassWater,
  'building': Building,
  'theater': Theater,
  'candle': Flame,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] || Sparkles;
}

export { type LucideIcon };
